using MermaidSharp.AutoDiagram.Tests.Models;
using MermaidSharp.Enums;

namespace MermaidSharp.AutoDiagram.Tests.ClassDiagrams
{
    /// <summary>
    /// Tests for <see cref="ClassDiagramExtension.ToMermaidClassDiagram(IEnumerable{Type}, ClassDiagramOptions)"/>.
    /// </summary>
    [TestClass]
    public class ClassDiagramExtensionTests
    {
        #region Constructors
        [TestMethod]
        public void ToMermaidClassDiagram_VisibilityOptions_RespectsPropertyAndMethodVisibility()
        {
            // Arrange
            var types = new[] { typeof(Person) };
            var expected = @"classDiagram
    class Person {
        +String FirstName
        +String LastName
        +get_FirstName()
        +set_FirstName()
        +get_LastName()
        +set_LastName()
        +SayHello()
        +GetType()
        +ToString()
        +Equals()
        +GetHashCode()
    }";

            // Act
            var diagram = types.ToMermaidClassDiagram();
            var result = diagram.CalculateDiagram();

            // Assert
            Assert.IsNotNull(result);
            Assert.AreEqual(expected, result);
        }

        [TestMethod]
        public void ToMermaidClassDiagram_CalculateDiagram_OutputContainsAllKeyElements()
        {
            // Arrange
            var types = new[] { typeof(Employee), typeof(Manager), typeof(IContactable), typeof(Department<Employee>) };
            var expected = @"classDiagram
    class Employee {
        +String EmployeeId
        +String Email
        +Department~Employee~ Department
        +String FirstName
        +String LastName
        +get_EmployeeId()
        +set_EmployeeId()
        +get_Email()
        +set_Email()
        +Contact()
        +get_Department() Employee
        +set_Department(Employee)
        +get_FirstName()
        +set_FirstName()
        +get_LastName()
        +set_LastName()
        +SayHello()
        +GetType()
        +ToString()
        +Equals()
        +GetHashCode()
    }
    class Manager {
        +Int32 Level
        +String EmployeeId
        +String Email
        +Department~Manager~ Department
        +String FirstName
        +String LastName
        +get_Level()
        +set_Level()
        +Approve()
        +get_EmployeeId()
        +set_EmployeeId()
        +get_Email()
        +set_Email()
        +Contact()
        +get_Department() Employee
        +set_Department(Employee)
        +get_FirstName()
        +set_FirstName()
        +get_LastName()
        +set_LastName()
        +SayHello()
        +GetType()
        +ToString()
        +Equals()
        +GetHashCode()
    }
    class IContactable {
        +String Email
        +get_Email()
        +set_Email()
        +Contact()
    }
    class Department~Employee~ {
        +String Name
        +List~Department~T~~ Members
        +get_Name()
        +set_Name()
        +get_Members() T
        +set_Members(T)
        +GetType()
        +ToString()
        +Equals()
        +GetHashCode()
    }
    Department-->Employee
    Department-->Manager";

            // Act
            var diagram = types.ToMermaidClassDiagram();
            var result = diagram.CalculateDiagram();

            // Assert
            Assert.IsNotNull(result);
            Assert.AreEqual(expected, result);
        }
        #endregion

        #region Assembly
        [TestMethod]
        public void ToMermaidClassDiagram_Assembly_GeneratesDiagramForAllTypes()
        {
            // Arrange
            var assembly = typeof(Employee).Assembly;
            var expected = @"classDiagram
    namespace MermaidSharp.AutoDiagram.Tests {
        class AutoGeneratedProgram {
            +GetType()
            +ToString()
            +Equals()
            +GetHashCode()
        }
        class Department~T~ {
            +String Name
            +List~Department~T~~ Members
            +get_Name()
            +set_Name()
            +get_Members() T
            +set_Members(T)
            +GetType()
            +ToString()
            +Equals()
            +GetHashCode()
        }
        class Employee {
            +String EmployeeId
            +String Email
            +Department~Employee~ Department
            +String FirstName
            +String LastName
            +get_EmployeeId()
            +set_EmployeeId()
            +get_Email()
            +set_Email()
            +Contact()
            +get_Department() Employee
            +set_Department(Employee)
            +get_FirstName()
            +set_FirstName()
            +get_LastName()
            +set_LastName()
            +SayHello()
            +GetType()
            +ToString()
            +Equals()
            +GetHashCode()
        }
        class IContactable {
            +String Email
            +get_Email()
            +set_Email()
            +Contact()
        }
        class Manager {
            +Int32 Level
            +String EmployeeId
            +String Email
            +Department~Manager~ Department
            +String FirstName
            +String LastName
            +get_Level()
            +set_Level()
            +Approve()
            +get_EmployeeId()
            +set_EmployeeId()
            +get_Email()
            +set_Email()
            +Contact()
            +get_Department() Employee
            +set_Department(Employee)
            +get_FirstName()
            +set_FirstName()
            +get_LastName()
            +set_LastName()
            +SayHello()
            +GetType()
            +ToString()
            +Equals()
            +GetHashCode()
        }
        class Person {
            +String FirstName
            +String LastName
            +get_FirstName()
            +set_FirstName()
            +get_LastName()
            +set_LastName()
            +SayHello()
            +GetType()
            +ToString()
            +Equals()
            +GetHashCode()
        }
        class ClassDiagramExtensionTests {
            +ToMermaidClassDiagram_ComplexModel_GeneratesCorrectNodesAndLinks()
            +ToMermaidClassDiagram_VisibilityOptions_RespectsPropertyAndMethodVisibility()
            +ToMermaidClassDiagram_CalculateDiagram_OutputContainsAllKeyElements()
            +ToMermaidClassDiagram_Assembly_GeneratesDiagramForAllTypes()
            +ToMermaidClassDiagram_Assembly_GeneratesDiagramForAllProperties()
            +GetType()
            +ToString()
            +Equals()
            +GetHashCode()
        }
    }
    Department-->Employee
    Department-->Manager";

            // Act
            var diagram = assembly.ToMermaidClassDiagram();
            var result = diagram.CalculateDiagram();

            // Assert
            Assert.IsNotNull(result);
            Assert.AreEqual(expected, result);
        }

        [TestMethod]
        public void ToMermaidClassDiagram_Assembly_GeneratesDiagramForAllProperties()
        {
            // Arrange
            var assembly = typeof(Employee).Assembly;
            var options = new ClassDiagramOptions()
            {
                IncludeMethodsVisibility = ClassPropertyVisibility.None
            };
            var expected = @"classDiagram
    namespace MermaidSharp.AutoDiagram.Tests {
        class AutoGeneratedProgram
        class Department~T~ {
            +String Name
            +List~Department~T~~ Members
        }
        class Employee {
            +String EmployeeId
            +String Email
            +Department~Employee~ Department
            +String FirstName
            +String LastName
        }
        class IContactable {
            +String Email
        }
        class Manager {
            +Int32 Level
            +String EmployeeId
            +String Email
            +Department~Manager~ Department
            +String FirstName
            +String LastName
        }
        class Person {
            +String FirstName
            +String LastName
        }
        class ClassDiagramExtensionTests
    }
    Department-->Employee
    Department-->Manager";

            // Act
            var diagram = assembly.ToMermaidClassDiagram(options);
            var result = diagram.CalculateDiagram();

            // Assert
            Assert.IsNotNull(result);
            Assert.AreEqual(expected, result);
        }

        #endregion
    }
}
